{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Jahr</th>\n",
       "      <th>Temperatur-Minimum(C)</th>\n",
       "      <th>Temperatur-Mittelwert(C)</th>\n",
       "      <th>Temperatur-Maximum(C)</th>\n",
       "      <th>Bodentemperatur-Minimum(C)</th>\n",
       "      <th>Sonnenstunden(h)</th>\n",
       "      <th>Relative Luftfeuchtigkeit(%)</th>\n",
       "      <th>Regen(mm)</th>\n",
       "      <th>Niederschlagsform(num)</th>\n",
       "      <th>Schnee(cm)</th>\n",
       "      <th>Neuschnee(cm)</th>\n",
       "      <th>Windgeschwindigkeit-Maximum(km/h)</th>\n",
       "      <th>Windgeschwindigkeit-Mittelwert(km/h)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1948-01-01</td>\n",
       "      <td>-5.0</td>\n",
       "      <td>-1.8</td>\n",
       "      <td>0.8</td>\n",
       "      <td>-4.7</td>\n",
       "      <td>n/A</td>\n",
       "      <td>89</td>\n",
       "      <td>5.7</td>\n",
       "      <td>8</td>\n",
       "      <td>4</td>\n",
       "      <td>n/A</td>\n",
       "      <td>n/A</td>\n",
       "      <td>n/A</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1948-01-02</td>\n",
       "      <td>-2.7</td>\n",
       "      <td>4.4</td>\n",
       "      <td>6.8</td>\n",
       "      <td>-2.5</td>\n",
       "      <td>n/A</td>\n",
       "      <td>95</td>\n",
       "      <td>3.3</td>\n",
       "      <td>1</td>\n",
       "      <td>8</td>\n",
       "      <td>n/A</td>\n",
       "      <td>n/A</td>\n",
       "      <td>n/A</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1948-01-03</td>\n",
       "      <td>5.2</td>\n",
       "      <td>8.5</td>\n",
       "      <td>10.6</td>\n",
       "      <td>4.6</td>\n",
       "      <td>n/A</td>\n",
       "      <td>86</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>n/A</td>\n",
       "      <td>n/A</td>\n",
       "      <td>n/A</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1948-01-04</td>\n",
       "      <td>6.6</td>\n",
       "      <td>10.2</td>\n",
       "      <td>11.5</td>\n",
       "      <td>4.7</td>\n",
       "      <td>n/A</td>\n",
       "      <td>83</td>\n",
       "      <td>0.2</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>n/A</td>\n",
       "      <td>n/A</td>\n",
       "      <td>n/A</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1948-01-05</td>\n",
       "      <td>8.0</td>\n",
       "      <td>10.5</td>\n",
       "      <td>12.0</td>\n",
       "      <td>5.9</td>\n",
       "      <td>n/A</td>\n",
       "      <td>78</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>n/A</td>\n",
       "      <td>n/A</td>\n",
       "      <td>n/A</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         Jahr  Temperatur-Minimum(C)  Temperatur-Mittelwert(C)  \\\n",
       "0  1948-01-01                   -5.0                      -1.8   \n",
       "1  1948-01-02                   -2.7                       4.4   \n",
       "2  1948-01-03                    5.2                       8.5   \n",
       "3  1948-01-04                    6.6                      10.2   \n",
       "4  1948-01-05                    8.0                      10.5   \n",
       "\n",
       "   Temperatur-Maximum(C)  Bodentemperatur-Minimum(C) Sonnenstunden(h)  \\\n",
       "0                    0.8                        -4.7              n/A   \n",
       "1                    6.8                        -2.5              n/A   \n",
       "2                   10.6                         4.6              n/A   \n",
       "3                   11.5                         4.7              n/A   \n",
       "4                   12.0                         5.9              n/A   \n",
       "\n",
       "  Relative Luftfeuchtigkeit(%) Regen(mm) Niederschlagsform(num) Schnee(cm)  \\\n",
       "0                           89       5.7                      8          4   \n",
       "1                           95       3.3                      1          8   \n",
       "2                           86         4                      1          0   \n",
       "3                           83       0.2                      1          0   \n",
       "4                           78         2                      1          0   \n",
       "\n",
       "  Neuschnee(cm) Windgeschwindigkeit-Maximum(km/h)  \\\n",
       "0           n/A                               n/A   \n",
       "1           n/A                               n/A   \n",
       "2           n/A                               n/A   \n",
       "3           n/A                               n/A   \n",
       "4           n/A                               n/A   \n",
       "\n",
       "  Windgeschwindigkeit-Mittelwert(km/h)  \n",
       "0                                  n/A  \n",
       "1                                  n/A  \n",
       "2                                  n/A  \n",
       "3                                  n/A  \n",
       "4                                  n/A  "
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from datetime import datetime as dt\n",
    "\n",
    "df = pd.read_csv('clima_data.csv')\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "temp = []\n",
    "yr = []\n",
    "\n",
    "for pos, d in df.iterrows():\n",
    "    temp.append(d[\"Temperatur-Mittelwert(C)\"])\n",
    "    yr.append(d[\"Jahr\"])\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Jahr                                    1979-02-18\n",
      "Temperatur-Minimum(C)                         -5.7\n",
      "Temperatur-Mittelwert(C)                      -2.2\n",
      "Temperatur-Maximum(C)                           -1\n",
      "Bodentemperatur-Minimum(C)                      -7\n",
      "Sonnenstunden(h)                                 0\n",
      "Relative Luftfeuchtigkeit(%)                    91\n",
      "Regen(mm)                                        0\n",
      "Niederschlagsform(num)                           6\n",
      "Schnee(cm)                                      55\n",
      "Neuschnee(cm)                                    5\n",
      "Windgeschwindigkeit-Maximum(km/h)              6.2\n",
      "Windgeschwindigkeit-Mittelwert(km/h)             4\n",
      "Name: 11371, dtype: object\n"
     ]
    }
   ],
   "source": [
    "snow = 20\n",
    "i = 0\n",
    "for pos, d in df.iterrows():\n",
    "    if d[\"Schnee(cm)\"] == \"n/A\":\n",
    "        continue\n",
    "    if int(d[\"Schnee(cm)\"]) > snow:\n",
    "        snow = int(d[\"Schnee(cm)\"])\n",
    "        i = pos\n",
    "for pos, d in df.iterrows():\n",
    "    if pos == i:\n",
    "        print(d)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Jahr</th>\n",
       "      <th>Temperatur-Minimum(C)</th>\n",
       "      <th>Temperatur-Mittelwert(C)</th>\n",
       "      <th>Temperatur-Maximum(C)</th>\n",
       "      <th>Bodentemperatur-Minimum(C)</th>\n",
       "      <th>Sonnenstunden(h)</th>\n",
       "      <th>Relative Luftfeuchtigkeit(%)</th>\n",
       "      <th>Regen(mm)</th>\n",
       "      <th>Niederschlagsform(num)</th>\n",
       "      <th>Schnee(cm)</th>\n",
       "      <th>Neuschnee(cm)</th>\n",
       "      <th>Windgeschwindigkeit-Maximum(km/h)</th>\n",
       "      <th>Windgeschwindigkeit-Mittelwert(km/h)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>26491</th>\n",
       "      <td>2020-07-12</td>\n",
       "      <td>10.4</td>\n",
       "      <td>16.3</td>\n",
       "      <td>21.9</td>\n",
       "      <td>5.3</td>\n",
       "      <td>9.933</td>\n",
       "      <td>58.13</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>n/A</td>\n",
       "      <td>n/A</td>\n",
       "      <td>12.4</td>\n",
       "      <td>3.7</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24194</th>\n",
       "      <td>2014-03-29</td>\n",
       "      <td>1.9</td>\n",
       "      <td>9.3</td>\n",
       "      <td>16.2</td>\n",
       "      <td>-2.7</td>\n",
       "      <td>9.9</td>\n",
       "      <td>82.96</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>n/A</td>\n",
       "      <td>n/A</td>\n",
       "      <td>6.3</td>\n",
       "      <td>2.1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23452</th>\n",
       "      <td>2012-03-17</td>\n",
       "      <td>5.3</td>\n",
       "      <td>11.9</td>\n",
       "      <td>20.9</td>\n",
       "      <td>-2.7</td>\n",
       "      <td>9.9</td>\n",
       "      <td>65</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>n/A</td>\n",
       "      <td>n/A</td>\n",
       "      <td>7.8</td>\n",
       "      <td>2.6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24213</th>\n",
       "      <td>2014-04-17</td>\n",
       "      <td>1.6</td>\n",
       "      <td>8.9</td>\n",
       "      <td>14.0</td>\n",
       "      <td>-5.2</td>\n",
       "      <td>9.9</td>\n",
       "      <td>50.21</td>\n",
       "      <td>3.5</td>\n",
       "      <td>4</td>\n",
       "      <td>n/A</td>\n",
       "      <td>n/A</td>\n",
       "      <td>11.2</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24222</th>\n",
       "      <td>2014-04-26</td>\n",
       "      <td>11.0</td>\n",
       "      <td>16.3</td>\n",
       "      <td>22.0</td>\n",
       "      <td>2.9</td>\n",
       "      <td>9.9</td>\n",
       "      <td>70.71</td>\n",
       "      <td>0.1</td>\n",
       "      <td>4</td>\n",
       "      <td>n/A</td>\n",
       "      <td>n/A</td>\n",
       "      <td>9.9</td>\n",
       "      <td>3.4</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "             Jahr  Temperatur-Minimum(C)  Temperatur-Mittelwert(C)  \\\n",
       "26491  2020-07-12                   10.4                      16.3   \n",
       "24194  2014-03-29                    1.9                       9.3   \n",
       "23452  2012-03-17                    5.3                      11.9   \n",
       "24213  2014-04-17                    1.6                       8.9   \n",
       "24222  2014-04-26                   11.0                      16.3   \n",
       "\n",
       "       Temperatur-Maximum(C)  Bodentemperatur-Minimum(C) Sonnenstunden(h)  \\\n",
       "26491                   21.9                         5.3            9.933   \n",
       "24194                   16.2                        -2.7              9.9   \n",
       "23452                   20.9                        -2.7              9.9   \n",
       "24213                   14.0                        -5.2              9.9   \n",
       "24222                   22.0                         2.9              9.9   \n",
       "\n",
       "      Relative Luftfeuchtigkeit(%) Regen(mm) Niederschlagsform(num)  \\\n",
       "26491                        58.13         0                      0   \n",
       "24194                        82.96         0                      0   \n",
       "23452                           65         0                      0   \n",
       "24213                        50.21       3.5                      4   \n",
       "24222                        70.71       0.1                      4   \n",
       "\n",
       "      Schnee(cm) Neuschnee(cm) Windgeschwindigkeit-Maximum(km/h)  \\\n",
       "26491        n/A           n/A                              12.4   \n",
       "24194        n/A           n/A                               6.3   \n",
       "23452        n/A           n/A                               7.8   \n",
       "24213        n/A           n/A                              11.2   \n",
       "24222        n/A           n/A                               9.9   \n",
       "\n",
       "      Windgeschwindigkeit-Mittelwert(km/h)  \n",
       "26491                                  3.7  \n",
       "24194                                  2.1  \n",
       "23452                                  2.6  \n",
       "24213                                    3  \n",
       "24222                                  3.4  "
      ]
     },
     "execution_count": 42,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df2 = df.sort_values(\"Sonnenstunden(h)\", ascending = False)\n",
    "\n",
    "df3 = df2[df2[\"Sonnenstunden(h)\"] != \"n/A\"]\n",
    "\n",
    "df3.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%matplotlib inline\n",
    "import matplotlib.pyplot as plt\n",
    "df = pd.read_csv('clima_data.csv')\n",
    "plt.plot(df[\"Jahr\"], df[\"Temperatur-Maximum(C)\"])\n",
    "plt.show"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
